//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addressItem
    {
        public addressItem()
        {
            this.addressid = new Guid();
        }
        public System.Guid addressid { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public Nullable<int> postcode { get; set; }
        public string suburb { get; set; }
        public string address1 { get; set; }
        public System.Guid merchantDetail_Id { get; set; }
    
        public virtual MerchantDetail MerchantDetail { get; set; }
    }
}
