//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MerchantDetail()
        {
            this.Id = new Guid();
            this.addressItems = new HashSet<addressItem>();
        }
    
        public System.Guid Id { get; set; }
        public string display_name { get; set; }
        public string registered_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string web_url { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string status { get; set; }
        public string logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<addressItem> addressItems { get; set; }
    }
}
